---
- hosts: all
  become: yes
  tasks:
    - name: ensure some packages are installed
      package:
        name: "{{ item }}"
        state: present
      loop:
        - htop
        - ncdu
        - neofetch
        - neovim
        - ranger
        - trash-cli
        - vim
